[plugin]
[plugin.k8s_secret]
mode="kubeconfig"
kubeconfig={type="path",value="k8s/minikube.kubeconfig"}
[plugin.k8s_configmap]
mode="kubeconfig"
kubeconfig={type="path",value="k8s/minikube.kubeconfig"}
