name: run ci/cd

on:
  push:
    branches: [ main ]

env:
  CONTAINER: gormja_core2

jobs:
  build-base:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build ts libs
        run: |
          cd my-ts-lib
          pwd
          ls -al
          npm install
          ./build.sh
          ls -al
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou  # 3
          username: "akaany"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: cp images to aliyun
        run: |
          docker build --tag registry.cn-hangzhou.aliyuncs.com/any-public/${{ env.CONTAINER }} .
          docker push registry.cn-hangzhou.aliyuncs.com/any-public/${{ env.CONTAINER }}